repos:
  - repo: local
    hooks:
      - id: npm-run-format
        name: Run Prettier
        entry: npm run format
        language: system
        types: [javascript, ts, yaml]
      - id: npm-run-lint
        name: Run ESLint
        entry: npm run lint
        language: system
        types: [javascript, ts, yaml]
